import __builtin__

HOST_IP_ADDRESS = "192.168.196.136"
PROGRAM_NAME = "BOT ARMY"
LOCK_LEFT_TERMINAL = False
PROGRAM_QUIT = False
SCANNED = { True: "YES", False:"NO"}
STATUS = { "1": "SLEEPING", "2":"ASSIGNED", "3":"PERMANENT ASSIGNMENT"}

__builtin__.SUBNET_HOSTS = {}

SHELLS = 0

BOT_COUNT = 0

BOT_THREADS = []